# Generated by Django 5.2.4 on 2025-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(help_text='Short professional title e.g., Full Stack Developer', max_length=150)),
                ('bio', models.TextField(help_text='Main About Me content')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('cv', models.FileField(blank=True, help_text='Optional CV/resume upload', null=True, upload_to='about/cv/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
