# Generated by Django 5.2.4 on 2025-07-19 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short professional title e.g., Full Stack Developer', max_length=150)),
                ('bio', models.TextField(help_text='Main About Me content')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('cv', models.FileField(blank=True, help_text='Optional CV/resume upload', null=True, upload_to='about/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
